version: "3.8"

services:
  app:
    build: ./src  # Ссылка на папку с Docerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: "redis"
    ports:
      - "6379:6379"


